kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.cm.name }}-config
  labels:
    {{- include "python-git.labels" . | nindent 4 }}
data:
  port_number: "{{ .Values.cm.portnumber }}"
